### ISSUE TITLE
Try to minimize the dependencies from the macros needed in the client crate

### ISSUE THREAD

**Issue by gbin** [copper-project/copper-rs#136]
A typical Copper user crate has dependencies like that:
```toml
[dependencies]
cu29 = { workspace = true }
cu29-derive = { workspace = true }
cu29-clock = { workspace = true }
cu29-helpers = { workspace = true }
cu29-traits = { workspace = true } # needed
cu29-unifiedlog = { workspace = true } # needed
cu29-log = { workspace = true }
cu29-log-runtime = { workspace = true }  # needed
cu29-log-derive = { workspace = true } # needed
bincode = { workspace = true }  # needed
```
All those "needed" ones are coming from the macros that just use them.

Find a way, maybe some prelude pattern to avoid this misery in the client code.
