### ISSUE TITLE
Improve the Generated project to be cross compilation friendly

### ISSUE THREAD

**Issue by gbin** [copper-project/copper-rs#234]
Change the template project so the log reader and its dependencies are behind a use flag.

It is annoying when you want to cross compile and it drags in Python... here an example of a Cargo.toml that works:

```toml
[package]
name = "drone"
version = "0.1.0"
edition = "2021"
default-run = "drone"

# The main executable of your application
[[bin]]
name = "drone"
path = "src/main.rs"

[[bin]]
name = "drone-logreader"
path = "src/logreader.rs"
required-features = ["logreader"] 

[dependencies]
cu29 = { version = "*" }
bincode = { version = "2.0.0-rc.3", features = ["derive"] }
cu29-helpers = { version = "*" }

[features]
default = [] 
logreader = ["Cu29-export"] 

[dependencies.cu29-export]
version = "*"
optional = true
```

see templates/README.md to see what I am talking about.
